### ISSUE TITLE
Item order in UI

### ISSUE THREAD

**Issue by originalfoo** [Archomeda/csl-ambient-sounds-tuner#16]
Would it be possible to re-order items somewhat to group related things?

For example, all the siren volumes next to each other (maybe also rename them to something like "Siren: Police" for example), environment together, animals together, etc...

**Comment by Archomeda** [comment]
That's a good idea and something I have been keeping in mind for a while already. Currently, I'm adding the sliders in the same order as the game uses it, [as you can see here](https://github.com/Archomeda/csl-ambient-sounds-tuner/blob/master/CSL%20Ambient%20Sounds%20Tuner/UI/AdvancedOptionsWindow.cs#L88-106).

But, as I'm sure you've noticed it already, the order result in-game is arbitrary (well, it looks that way). It's possible that this is a side-effect of using the auto layout. I haven't looked at why the game orders it this way. Sadly, I will have to figure that out before I can order it manually :cry:

**Comment by Archomeda** [comment]
Update: I managed to get it working on a separate branch.
